<?php

namespace ActualSkill\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerPositionRepository extends EntityRepository
{
    
    public function findAllOrderByASC(){
        

        $query = $this->getEntityManager()
            ->createQuery('
                SELECT p FROM ActualSkillCoreBundle:PlayerPosition p
                ORDER BY p.sort_order ASC'
            );

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }        
        
    }
}