<?php

namespace ActualSkill\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    
    public function findOneBySlugJoinedToRatingSchema($slug)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT p, r FROM ActualSkillCoreBundle:Player p
                JOIN p.ratingschema r
                WHERE p.slug = :slug'
            )->setParameter('slug', $slug);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }    
   
}