imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    translator:      { fallback: en }
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
      facebook_comments_base_href: http://www.actualskill.com

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: false           

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: ActualSkill\CoreBundle\Entity\User
    use_listener: true
    use_username_form_type: false
    from_email:
        address: troelsjohnsen@gmail.com
        sender_name: ActualSkill.com
    registration:
        form:
          type: actualskill_user_registration        
        
stof_doctrine_extensions: 
    orm: 
        default: 
            sluggable: true
            timestampable: true

fos_js_routing:
    routes_to_expose: [ "player_show", "club_show" ]
            
#fos_facebook:
#      file:   %kernel.root_dir%/../vendor/facebook/src/base_facebook.php
#      alias:  facebook
#      app_id: 199966153372036
#      secret: b3bb156ca48dcafe92f64e28951e0987
#      cookie: true
#      permissions: [email, user_birthday, user_location]            