<?php

namespace ActualSkill\SharedEntityBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    
    public function getAverageRating(\ActualSkill\SharedEntityBundle\Entity\Player $player){
        
        return $this->getEntityManager()
            ->createQuery('SELECT AVG(r.rating) as average FROM ActualSkillSharedEntityBundle:Rating r WHERE r.object = ?1 GROUP BY r.attribute')
            ->setParameter(1, $player->getId())
            ->getResult();        
    }
}