<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ActualSkillSiteBundleEntityClubProxy extends \ActualSkill\SiteBundle\Entity\Club implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function setShortname($shortname)
    {
        $this->__load();
        return parent::setShortname($shortname);
    }

    public function getShortname()
    {
        $this->__load();
        return parent::getShortname();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function setCountry(\ActualSkill\SiteBundle\Entity\Country $country)
    {
        $this->__load();
        return parent::setCountry($country);
    }

    public function getCountry()
    {
        $this->__load();
        return parent::getCountry();
    }

    public function setStadium(\ActualSkill\SiteBundle\Entity\Stadium $stadium)
    {
        $this->__load();
        return parent::setStadium($stadium);
    }

    public function getStadium()
    {
        $this->__load();
        return parent::getStadium();
    }

    public function setType($type)
    {
        $this->__load();
        return parent::setType($type);
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function addRatings(\ActualSkill\SiteBundle\Entity\Rating $ratings)
    {
        $this->__load();
        return parent::addRatings($ratings);
    }

    public function getRatings()
    {
        $this->__load();
        return parent::getRatings();
    }

    public function addComments(\ActualSkill\SiteBundle\Entity\Comment $comments)
    {
        $this->__load();
        return parent::addComments($comments);
    }

    public function getComments()
    {
        $this->__load();
        return parent::getComments();
    }

    public function setSlug($slug)
    {
        $this->__load();
        return parent::setSlug($slug);
    }

    public function getSlug()
    {
        $this->__load();
        return parent::getSlug();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'slug', 'name', 'ratings', 'comments', 'shortname', 'country', 'stadium');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}